<?php component('html-head-new') ?>
<?php component('header-new') ?>
<?php component('Hero') ?>
<?php component('trader-new') ?>
<?php component('mentor') ?>
<?php component('review') ?>
<?php component('TestimonialDesign1') ?>
<?php component('Footer') ?>
<?php component('HtmlEnd') ?>