<?php component('Head') ?>
<?php component('HeaderStyle1') ?>
<?php component('SearchBoxDesign1') ?>
<?php component('BusinessDetailsDesign1') ?>
<?php component('SocialLinksDesign1') ?>
<?php component('BusinessInfoWithSidebarAndCustomerReviewDesign1') ?>
<?php component('RecommendDesign1') ?>
<?php component('FooterStyle1') ?>
<?php component('Profilepagejs') ?>
<?php component('Htmlend') ?>